#!/bin/bash

systemctl stop wg-quick@wg0.service || exit 1

client_name1=`shuf -n1 /usr/share/dict/words | tr -d '[:punct:]'`
client_name2=`shuf -n1 /usr/share/dict/words | tr -d '[:punct:]'`
client_name="${client_name1}_${client_name2}"

cd /etc/wireguard/keys || exit 1
wg genkey | tee ${client_name}.prv.key | wg pubkey > ${client_name}.pub.key
clientPubKey=`cat /etc/wireguard/keys/${client_name}.pub.key`


clientPrvKey=`cat /etc/wireguard/keys/${client_name}.prv.key`
publicKey=`cat /etc/wireguard/keys/publickey`
extIp=`dig @resolver1.opendns.com ANY myip.opendns.com +short`

touch /etc/wireguard/clients/$client_name.conf

echo '[Interface]' >> /etc/wireguard/clients/$client_name.conf
echo "PrivateKey = $clientPrvKey" >> /etc/wireguard/clients/$client_name.conf
echo 'Address = 192.168.5.2/32' >> /etc/wireguard/clients/$client_name.conf
echo 'DNS = 1.1.1.1' >> /etc/wireguard/clients/$client_name.conf
echo 'ListenPort = 51820' >> /etc/wireguard/clients/$client_name.conf
echo '' >> /etc/wireguard/clients/$client_name.conf
echo '[Peer]' >> /etc/wireguard/clients/$client_name.conf
echo "PublicKey = $publicKey" >> /etc/wireguard/clients/$client_name.conf
echo "Endpoint = $extIp:51820" >> /etc/wireguard/clients/$client_name.conf
echo 'AllowedIPs = 0.0.0.0/0, ::/0' >> /etc/wireguard/clients/$client_name.conf

echo '' >> /etc/wireguard/wg0.conf
echo '[Peer]' >> /etc/wireguard/wg0.conf
echo "PublicKey = $clientPubKey" >> /etc/wireguard/wg0.conf
echo 'AllowedIPs = 192.168.5.2/32' >> /etc/wireguard/wg0.conf

qrencode -t ansiutf8 < /etc/wireguard/clients/$client_name.conf > /home/ia/$client_name.qr

systemctl start wg-quick@wg0.service || exit 1
echo systemctl show -p SubState --value wg0.service

exit 0
